version: "3"
services:
    mysql:
      image: mysql:${MYSQL_VERSION}
      container_name: track-me-mysql
      restart: always
      volumes:
        - ./docker/mysql/records.sql:/docker-entrypoint-initdb.d/records.sql
        - ./docker/data/db:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "8989:3306"

    webserver:
      image: nginx:alpine
      container_name: track-me-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"
      restart: always
      depends_on:
        - php-fpm
        - mysql

    php-fpm:
      build: docker/php-fpm
      container_name: track-me-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

